In [1]:
import pandas as pd
import numpy as np

In [32]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data"

columns = [
    "age", "workclass", "fnlwgt", "education", "education-num",
    "marital-status", "occupation", "relationship", "race",
    "sex", "capital-gain", "capital-loss",
    "hours-per-week", "native-country", "income"
]

data = pd.read_csv(
    url,
    names=columns,
    skipinitialspace=True,
    na_values="?"
)

data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K

In [13]:
print(data.shape)
print(data.info())
print(data.describe())

(32561, 15)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32561 entries, 0 to 32560
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   age             32561 non-null  int64
 1   workclass       30725 non-null  object
 2   fnlwgt          32561 non-null  int64
 3   education       32561 non-null  object
 4   education-num   32561 non-null  int64
 5   marital-status  32561 non-null  object
 6   occupation      30718 non-null  object
 7   relationship    32561 non-null  object
 8   race            32561 non-null  object
 9   sex             32561 non-null  object
 10  capital-gain    32561 non-null  int64
 11  capital-loss    32561 non-null  int64
 12  hours-per-week  32561 non-null  int64
 13  native-country  31978 non-null  object
 14  income          32561 non-null  object
dtypes: int64(6), object(9)
memory usage: 3.7+ MB
None
                age        fnlwgt  education-num  capital-gain  capital-loss  \
count  32561.000000  3.256100e+04   32561.000000  32561.000000  32561.000000
mean      38.581647  1.897784e+05      10.080679   1077.648844     87.303830
std       13.640433  1.055500e+05       2.572720   7385.292085    402.960219
min       17.000000  1.228500e+04       1.000000      0.000000      0.000000
25%       28.000000  1.178270e+05       9.000000      0.000000      0.000000
50%       37.000000  1.783560e+05      10.000000      0.000000      0.000000
75%       48.000000  2.370510e+05      12.000000      0.000000      0.000000
max       90.000000  1.484705e+06      16.000000  99999.000000   4356.000000

       hours-per-week
count    32561.000000
mean        40.437456
std         12.347429
min          1.000000
25%         40.000000
50%         40.000000
75%         45.000000
max         99.000000

In [14]:
print(data.isnull().sum())

age                  0
workclass         1836
fnlwgt               0
education            0
education-num        0
marital-status       0
occupation        1843
relationship         0
race                 0
sex                  0
capital-gain         0
capital-loss         0
hours-per-week       0
native-country     583
income               0
dtype: int64

In [15]:
for column in data.select_dtypes(include="object"):
    data[column].fillna(data[column].mode()[0], inplace=True)

for column in data.select_dtypes(include=np.number):
    data[column].fillna(data[column].mean(), inplace=True)

print(data.isnull().sum())

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
income            0
dtype: int64

C:\Users\anits-csm\AppData\Local\Temp\ipykernel_1716\3050968993.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(data[column].mode()[0], inplace=True)
C:\Users\anits-csm\AppData\Local\Temp\ipykernel_1716\3050968993.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data[column].fillna(data[column].mean(), inplace=True)

In [16]:
data.loc[0, "age"] = 150
print(data.head())

   age         workclass  fnlwgt  education  education-num  \
0  150         State-gov   77516  Bachelors             13
1   50  Self-emp-not-inc   83311  Bachelors             13
2   38           Private  215646    HS-grad              9
3   53           Private  234721       11th              7
4   28           Private  338409  Bachelors             13

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male
1  Married-civ-spouse    Exec-managerial        Husband  White    Male
2            Divorced  Handlers-cleaners  Not-in-family  White    Male
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female

   capital-gain  capital-loss  hours-per-week native-country income
0          2174             0              40  United-States  <=50K
1             0             0              13  United-States  <=50K
2             0             0              40  United-States  <=50K
3             0             0              40  United-States  <=50K
4             0             0              40           Cuba  <=50K

In [17]:
median_age = data["age"].median()

data.loc[0, "age"] = median_age

print(data.head())

   age         workclass  fnlwgt  education  education-num  \
0   37         State-gov   77516  Bachelors             13
1   50  Self-emp-not-inc   83311  Bachelors             13
2   38           Private  215646    HS-grad              9
3   53           Private  234721       11th              7
4   28           Private  338409  Bachelors             13

       marital-status         occupation   relationship   race     sex  \
0       Never-married       Adm-clerical  Not-in-family  White    Male
1  Married-civ-spouse    Exec-managerial        Husband  White    Male
2            Divorced  Handlers-cleaners  Not-in-family  White    Male
3  Married-civ-spouse  Handlers-cleaners        Husband  Black    Male
4  Married-civ-spouse     Prof-specialty           Wife  Black  Female

   capital-gain  capital-loss  hours-per-week native-country income
0          2174             0              40  United-States  <=50K
1             0             0              13  United-States  <=50K
2             0             0              40  United-States  <=50K
3             0             0              40  United-States  <=50K
4             0             0              40           Cuba  <=50K

In [18]:
Q1 = data["age"].quantile(0.25)
Q3 = data["age"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = data[(data["age"] < lower) | (data["age"] > upper)]

print(outliers)

       age         workclass  fnlwgt     education  education-num  \
74      79           Private  124744  Some-college             10
222     90           Private   51744       HS-grad              9
430     80           Private  107762       HS-grad              9
918     81  Self-emp-not-inc  136063       HS-grad              9
1040    90           Private  137018       HS-grad              9
...    ...               ...     ...           ...            ...
32277   90           Private  313749       HS-grad              9
32367   90         Local-gov  214594       7th-8th              4
32459   85           Private   98611     Bachelors             13
32494   82           Private  403910       HS-grad              9
32525   81           Private  120478     Assoc-voc             11

           marital-status       occupation    relationship   race     sex  \
74     Married-civ-spouse   Prof-specialty  Other-relative  White    Male
222         Never-married    Other-service   Not-in-family  Black    Male
430               Widowed   Prof-specialty   Not-in-family  White    Male
918    Married-civ-spouse  Exec-managerial         Husband  White    Male
1040        Never-married    Other-service   Not-in-family  White  Female
...                   ...              ...             ...    ...     ...
32277             Widowed     Adm-clerical       Unmarried  White  Female
32367  Married-civ-spouse  Protective-serv         Husband  White    Male
32459  Married-civ-spouse  Exec-managerial         Husband  White    Male
32494       Never-married   Prof-specialty   Not-in-family  White    Male
32525            Divorced   Prof-specialty       Unmarried  White  Female

       capital-gain  capital-loss  hours-per-week native-country income
74                0             0              20  United-States  <=50K
222               0          2206              40  United-States  <=50K
430               0             0              24  United-States  <=50K
918               0             0              30  United-States  <=50K
1040              0             0              40  United-States  <=50K
...             ...           ...             ...            ...    ...
32277             0             0              25  United-States  <=50K
32367          2653             0              40  United-States  <=50K
32459             0             0               3         Poland  <=50K
32494             0             0               3  United-States  <=50K
32525             0             0               1  United-States  <=50K

[143 rows x 15 columns]

In [19]:
data = data[(data["age"] >= lower) & (data["age"] <= upper)]

In [20]:
department = pd.DataFrame({
    "age":[25,30,35],
    "Department":["HR","Sales","IT"]
})

print(department)

   age Department
0   25         HR
1   30      Sales
2   35         IT

In [21]:
merged = pd.merge(
    data,
    department,
    on="age",
    how="left"
)

merged.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,Department
0,37,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K,NaN
1,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K,NaN
2,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K,NaN
3,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K,NaN
4,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K,NaN

In [22]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

numeric_columns = data.select_dtypes(include=np.number).columns

data[numeric_columns] = scaler.fit_transform(data[numeric_columns])

data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,0.327869,State-gov,0.044302,Bachelors,0.800000,Never-married,Adm-clerical,Not-in-family,White,Male,0.02174,0.0,0.397959,United-States,<=50K
1,0.540984,Self-emp-not-inc,0.048238,Bachelors,0.800000,Married-civ-spouse,Exec-managerial,Husband,White,Male,0.00000,0.0,0.122449,United-States,<=50K
2,0.344262,Private,0.138113,HS-grad,0.533333,Divorced,Handlers-cleaners,Not-in-family,White,Male,0.00000,0.0,0.397959,United-States,<=50K
3,0.590164,Private,0.151068,11th,0.400000,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0.00000,0.0,0.397959,United-States,<=50K
4,0.180328,Private,0.221488,Bachelors,0.800000,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0.00000,0.0,0.397959,Cuba,<=50K

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

data[numeric_columns] = scaler.fit_transform(data[numeric_columns])

data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income
0,-0.103644,State-gov,-1.064316,Bachelors,1.135916,Never-married,Adm-clerical,Not-in-family,White,Male,0.148357,-0.216866,-0.039957,United-States,<=50K
1,0.871623,Self-emp-not-inc,-1.009439,Bachelors,1.135916,Married-civ-spouse,Exec-managerial,Husband,White,Male,-0.145585,-0.216866,-2.235706,United-States,<=50K
2,-0.028624,Private,0.243734,HS-grad,-0.421821,Divorced,Handlers-cleaners,Not-in-family,White,Male,-0.145585,-0.216866,-0.039957,United-States,<=50K
3,1.096685,Private,0.424369,11th,-1.200690,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,-0.145585,-0.216866,-0.039957,United-States,<=50K
4,-0.778830,Private,1.406264,Bachelors,1.135916,Married-civ-spouse,Prof-specialty,Wife,Black,Female,-0.145585,-0.216866,-0.039957,Cuba,<=50K

In [24]:
average = data.groupby("income")["age"].mean()

print(average)

income
<=50K   -0.136883
>50K     0.430858
Name: age, dtype: float64

In [25]:
bins = [0,25,45,65,100]

labels = ["Young","Adult","Middle Age","Senior"]

data["Age_Group"] = pd.cut(
    data["age"],
    bins=bins,
    labels=labels
)

print(data[["age","Age_Group"]].head())

        age Age_Group
0 -0.103644       NaN
1  0.871623     Young
2 -0.028624       NaN
3  1.096685     Young
4 -0.778830       NaN

In [26]:
from sklearn.preprocessing import LabelEncoder

encoder = LabelEncoder()

categorical_columns = data.select_dtypes(include="object").columns

for column in categorical_columns:
    data[column] = encoder.fit_transform(data[column])

data.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income,Age_Group
0,-0.103644,6,-1.064316,9,1.135916,4,0,1,4,1,0.148357,-0.216866,-0.039957,38,0,NaN
1,0.871623,5,-1.009439,9,1.135916,2,3,0,4,1,-0.145585,-0.216866,-2.235706,38,0,Young
2,-0.028624,3,0.243734,11,-0.421821,0,5,1,4,1,-0.145585,-0.216866,-0.039957,38,0,NaN
3,1.096685,3,0.424369,1,-1.200690,2,5,0,2,1,-0.145585,-0.216866,-0.039957,38,0,Young
4,-0.778830,3,1.406264,9,1.135916,2,9,5,2,0,-0.145585,-0.216866,-0.039957,4,0,NaN

In [27]:
encoded = pd.get_dummies(data, columns=["sex"])

encoded.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,capital-gain,capital-loss,hours-per-week,native-country,income,Age_Group,sex_0,sex_1
0,-0.103644,6,-1.064316,9,1.135916,4,0,1,4,0.148357,-0.216866,-0.039957,38,0,NaN,False,True
1,0.871623,5,-1.009439,9,1.135916,2,3,0,4,-0.145585,-0.216866,-2.235706,38,0,Young,False,True
2,-0.028624,3,0.243734,11,-0.421821,0,5,1,4,-0.145585,-0.216866,-0.039957,38,0,NaN,False,True
3,1.096685,3,0.424369,1,-1.200690,2,5,0,2,-0.145585,-0.216866,-0.039957,38,0,Young,False,True
4,-0.778830,3,1.406264,9,1.135916,2,9,5,2,-0.145585,-0.216866,-0.039957,4,0,NaN,True,False

In [28]:
X = data.drop("income", axis=1)

y = data["income"]

print(X.head())

        age  workclass    fnlwgt  education  education-num  marital-status  \
0 -0.103644          6 -1.064316          9       1.135916               4
1  0.871623          5 -1.009439          9       1.135916               2
2 -0.028624          3  0.243734         11      -0.421821               0
3  1.096685          3  0.424369          1      -1.200690               2
4 -0.778830          3  1.406264          9       1.135916               2

   occupation  relationship  race  sex  capital-gain  capital-loss  \
0           0             1     4    1      0.148357     -0.216866
1           3             0     4    1     -0.145585     -0.216866
2           5             1     4    1     -0.145585     -0.216866
3           5             0     2    1     -0.145585     -0.216866
4           9             5     2    0     -0.145585     -0.216866

   hours-per-week  native-country Age_Group
0       -0.039957              38       NaN
1       -2.235706              38     Young
2       -0.039957              38       NaN
3       -0.039957              38     Young
4       -0.039957               4       NaN

In [35]:
sample = data.sample(
    n=1000,
    random_state=42
)

print(sample.head())

       age         workclass  fnlwgt     education  education-num  \
14160   27           Private  160178  Some-college             10
27048   45         State-gov   50567       HS-grad              9
28868   29           Private  185908     Bachelors             13
5667    30           Private  190040     Bachelors             13
7827    29  Self-emp-not-inc  189346  Some-college             10

           marital-status         occupation   relationship   race     sex  \
14160            Divorced       Adm-clerical  Not-in-family  White  Female
27048  Married-civ-spouse    Exec-managerial           Wife  White  Female
28868  Married-civ-spouse    Exec-managerial        Husband  Black    Male
5667        Never-married  Machine-op-inspct  Not-in-family  White  Female
7827             Divorced       Craft-repair  Not-in-family  White    Male

       capital-gain  capital-loss  hours-per-week native-country income
14160             0             0              38  United-States  <=50K
27048             0             0              40  United-States  <=50K
28868             0             0              55  United-States   >50K
5667              0             0              40  United-States  <=50K
7827           2202             0              50  United-States  <=50K

In [37]:
from sklearn.model_selection import train_test_split

X = data.drop("income", axis=1)

y = data["income"]

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", X_train.shape)
print("Testing Data:", X_test.shape)

Training Data: (26048, 14)
Testing Data: (6513, 14)